# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umkarticles',
            name='kursovya_hours',
            field=models.CharField(default=0, max_length=10, null=True, verbose_name='Количество часов на курсовую работу,часов'),
        ),
        migrations.AlterField(
            model_name='umkarticles',
            name='kursovya_semestr',
            field=models.CharField(default='0', max_length=15, null=True, verbose_name='Номер cеместра на курсовую'),
        ),
        migrations.AlterField(
            model_name='umkarticles',
            name='raschetnograp_work_hours',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='Количество часов на расчетно-графическую работу, часов'),
        ),
        migrations.AlterField(
            model_name='umkarticles',
            name='raschetnograp_work_semestr',
            field=models.CharField(default='0', max_length=15, null=True, verbose_name='Номер семестра на расчетно-графическую работу'),
        ),
    ]
