# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180726_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkarticles',
            name='kursovya_hours',
        ),
        migrations.RemoveField(
            model_name='umkarticles',
            name='kursovya_semestr',
        ),
        migrations.RemoveField(
            model_name='umkarticles',
            name='raschetnograp_work_hours',
        ),
        migrations.RemoveField(
            model_name='umkarticles',
            name='raschetnograp_work_semestr',
        ),
        migrations.AddField(
            model_name='umkdata',
            name='kursovya_hours',
            field=models.CharField(default='0', max_length=10, verbose_name='Количество часов на курсовую работу,часов'),
        ),
        migrations.AddField(
            model_name='umkdata',
            name='kursovya_semestr',
            field=models.CharField(default='0', max_length=15, verbose_name='Номер cеместра на курсовую'),
        ),
        migrations.AddField(
            model_name='umkdata',
            name='raschetnograp_work_hours',
            field=models.CharField(default='0', max_length=10, verbose_name='Количество часов на расчетно-графическую работу, часов'),
        ),
        migrations.AddField(
            model_name='umkdata',
            name='raschetnograp_work_semestr',
            field=models.CharField(default='0', max_length=15, verbose_name='Номер семестра на расчетно-графическую работу'),
        ),
        migrations.AlterField(
            model_name='umkdata',
            name='database_info_system',
            field=models.TextField(blank=True, null=True, verbose_name='Базы данных, информационно-справочные и поисковые системы'),
        ),
        migrations.AlterField(
            model_name='umkdata',
            name='umk_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UmkArticles', verbose_name='ID рабочей программы'),
        ),
    ]
