# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180726_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkdata',
            name='placeInStruct',
        ),
        migrations.AddField(
            model_name='plans',
            name='weeks_count_in_semestr',
            field=models.CharField(blank=True, help_text='Формат: 17,18', max_length=20, null=True, verbose_name='Количество недель в семестре'),
        ),
        migrations.AddField(
            model_name='umkarticles',
            name='datetime_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='umkarticles',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='umkarticles',
            name='status',
            field=models.CharField(choices=[['edit', 'Наполнение'], ['signaturing', 'На подписи'], ['confirmed', 'Подписана'], ['empty', 'Пустая']], default='empty', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='umkdata',
            name='kursovya_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество часов на курсовую работу,часов'),
        ),
        migrations.AlterField(
            model_name='umkdata',
            name='raschetnograp_work_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество часов на расчетно-графическую работу, часов'),
        ),
    ]
