# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_umkdata_software_lic'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkdata',
            name='kos',
            field=models.TextField(blank=True, null=True, verbose_name='Комплект оценочных средств'),
        ),
    ]
